### ISSUE TITLE
Signed in locally

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10368]
We want to be able to be signed-in locally so we can test without having to deploy to CODE

**Comment by georgeblahblah** [comment]
Having spoken with the identity team, we see three options:

## Option 1: Proxy with `*.thegulocal.com`

For this to work, we need to:

- set up proxying for  Discussion API in `manage-frontend`, like how `profile.thegulocal.com` points to CODE, so cookies are passed along in the requests correctly
- rewrite config contained in the JSON payload from Frontend to point to the relevant `*.thegulocal.com` domain

## Option 2: use Okta tokens

This option probably requires more work. It involves making the relevant Okta tokens work across thegulocal/CODE domains so that they validate correctly.

## Option 3: dev server mocking

As previously discussed in WebX, mock "effects" like interacting with Discussion API/Identity API so that we can control responses on the dev server. This would bypass the need to set and send valid cookies as we would not need to make network requests.

**Comment by shesah** [comment]
Won't do - Will wait until OKTA is turned back on
