### ISSUE TITLE
Unnecessary scrollbars 

### ISSUE THREAD

**Issue by WillsB3** [guardian/dotcom-rendering#1039]
Hi 👋 

Just read https://www.theguardian.com/info/2019/dec/08/migrating-the-guardian-website-to-react and noticed that is unintended horizontal overflow. Notice the horizontal scrollbar at the bottom of the window:

<img width="2558" alt="Screenshot 2019-12-20 at 12 14 36" src="https://user-images.githubusercontent.com/868834/71254261-54fdc980-2322-11ea-9cf5-5bc534c88778.png">

From some very brief debugging (and being unfamiliar with your codebase). I believe the issue may stem from the following: 

<img width="446" alt="Screenshot 2019-12-20 at 12 22 20" src="https://user-images.githubusercontent.com/868834/71254604-65fb0a80-2323-11ea-9680-ac56407f20c7.png">

If I change `width: 100vw` to `width: 100%` the horizontal scrollbar disappears. This causes the layout of this section to change slightly so obviously other styles here would need to be adjusted to keep the section visually unchanged. 

To avoid these sorts of issues going undetected in stuff I work on, I set `Show scroll bars: Always` in MacOS general preference pane

<img width="780" alt="Screenshot 2019-12-20 at 12 13 43" src="https://user-images.githubusercontent.com/868834/71254368-9a21fb80-2322-11ea-824e-1d189a5a5122.png">

Thanks for the article and hope this helps

**Comment by oliverlloyd** [comment]
Hi @WillsB3 👋 and thanks for raising this issue!

This looks _similar_ to [another issue](https://trello-attachments.s3.amazonaws.com/5a903bfccad3736b2f8c6970/5dbb1883f298e12ed7b1554b/63c43ccaa0005040b4fa0f1a8911407a/image.png) where, at smaller screen widths, outbrain is pushing out of the viewport quite a bit

@shtukas I've linked this ticket to the trello card. It's similar but not the same so definately worth checking for in any fix

**Comment by oliverlloyd** [comment]
I've created https://github.com/guardian/dotcom-rendering/pull/1062 to address this issue

**Comment by WillsB3** [comment]
🎉

**Comment by paperboyo** [comment]
Has https://github.com/guardian/dotcom-rendering/pull/1062 also fixed https://github.com/guardian/frontend/issues/22170 ?

**Comment by oliverlloyd** [comment]
A PR double whammy? That would be nice. However, when I tested this on Android just now I spotted a different horizontal scrolling issue with an inline ad slot (which I've raised with commercial).

It's possible this is a different issue to the one raised in [guardian/frontend#22170](https://github.com/guardian/frontend/issues/22170) though so I'll be sure to check later once this issue is fixed

**Comment by oliverlloyd** [comment]
So, interestingly, it looks like frontend solves these Outbrain horizontal scrolling issues by slapping an `overflow: hidden` [on the container](https://github.com/guardian/frontend/blob/cea63f26fff63c380e4029c4569995fc1dcb43ff/static/src/stylesheets/amp/_facia.scss#L6).

There are definitely multiple issues here but at least one of them is directly caused by the Outbrain code having hard coded widths that are greater than the viewport and in this case the overflow hidden hammer is a good solution.

**Comment by oliverlloyd** [comment]
🔨: https://github.com/guardian/dotcom-rendering/pull/1066

This solves our Outbrain scrolling issues once and for all (hopefully!)
