### ISSUE TITLE
Implement Recommend on Android

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10654]

**Comment by alinaboghiu** [comment]
https://github.com/guardian/android-news-app/pull/10044

**Comment by ioannakok** [comment]
Update after a discussion with @robksmith, @EnochHankombo92 and @ab-gnm (meeting notes [here](https://docs.google.com/document/d/1in6nErIgtP3qObZJCvj4IyCh-BO7O2n9Ou1HHcXdEvE/edit)) and some thoughts after chatting with @georgeblahblah: 

### `AsyncIface` not working in the Android integration yet

In:
* https://github.com/guardian/android-news-app/pull/10044 

we tried to use the `AsyncIface` but as was initially suggested by @ab-gnm in the [review](https://github.com/guardian/android-news-app/pull/10044#discussion_r1497878745) this is not working in the Android integration yet. 

@robksmith and @ioannakok verified this:
* We tried to run [#10044](https://github.com/guardian/android-news-app/pull/10044) locally but only the UI gets updated and result does not persist.
* Added logging in a [branch](https://github.com/guardian/android-news-app/compare/main...rks/bridget/experimental) and noticed `recommend` does not get called
* Replaced `AsyncIface` with `Iface` and saw the logs from `recommend` coming through

@ab-gnm has a draft PR to get `AsyncIface` working but this work has not been completed yet:

* https://github.com/guardian/android-news-app/pull/9904

### Current options (until `AsyncIface` works) and consequences

* Use `Iface` like [`NotificationsImpl`](https://github.com/guardian/android-news-app/blob/main/android-news-app/src/main/java/com/guardian/feature/renderedarticle/bridget/NotificationsImpl.kt#L14) is doing at the moment for the follow button functionality
* Downside is the [`follow` method](https://github.com/guardian/android-news-app/blob/main/android-news-app/src/main/java/com/guardian/feature/renderedarticle/bridget/NotificationsImpl.kt#L16-L19) is currently returning true no matter what the real outcome of the request is.
*  An alternative possibility was mentioned in the meeting re using the main thread for Bridget-Android communication but this sounds risky.

### Thoughts / Questions
* Could we use `Iface` temporarily in order to get _only_ the `recommend` comment functionality to prod?
* This doesn't look like an option though for posting / replying to a comment & adding a username. Possible workaround suggested by the Android team until the `AsyncIface` works: Store comments in a local cache and try to repeat posting them. This will mean possible delays from when a user posts a comment until the action is actually completed.
* Even if we used the local cache option temporarily there are [many different types of errors](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/lib/discussion.ts#L161-L176) the discussion api could return. Could the local cache option handle this?
* If we decide to wait until the `AsyncIface` works in order to implement  posting / replying to a comment & adding a username, does this mean this work gets blocked for iOS as well?

**Comment by ioannakok** [comment]
We had a team discussion with @abeddow91, @daniel-guardian, @georgeblahblah and @arelra about this. Notes [here](https://docs.google.com/document/d/1IWLZFV30zFRJXKuw8qnEcWoMXWdNSiKFakumMgwdJV8/edit)  

It looks like we have three options at the moment:
1. Proceed with the features of discussion we think it’s ok to be optimistically updated, e.g. recommend
2. Re-write bridget models to request authentication tokens and do all the async communication in the web layer. This would change the current flow.
3. Mixed release: Implement everything on iOS, update MAPI and leave Android one version behind. We can combine this with option 1 by doing first releases of discussion features where we can optimistically update the UI (e.g. recommend) 

Before we decide which option we would like to get PMs / EMs to discuss when the async work can be planned / prioritised in their current stream of work. The goal would be to get a better understanding of the timeline not so much to do it asap.

**Comment by georgeblahblah** [comment]
Closing as this is ready to go to beta. We can reopen if there are any more issues.
