### ISSUE TITLE
Prevent `strong` tags inside `h2` elements having bold font weight applied

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#11049]
Prevent `<strong>` tags from appearing with a bold font weight in subheadings.

Stripping out the `<strong>` tags entirely from the HTML was considered but designers aren't keen since this is used to style interactives where they use the h2 strong vs. h2 normal to target two different h2s separately and style them with their own css

**Comment by paperboyo** [comment]
Useless comment:

this reminds me of somepin that is bugging me: ideally no styling changes from Tools would ever be ignored*. More so: whenever Design/platforms decide something to have a certain styling override (eg. a quote, coming in from Tools as regular, is being automatically italicised), and incoming quote text includes explicit italics part, platforms should then **force** unitalicising** of that italicised part.

Sounds complicated and counter-intuitive until you see it this happening in a book.

*yes, it means we would unearth any inconsistencies (when folks are emboldening H2s), but the alternative is worse: when we eventually fix it, there’s gonna be these styling decisions we ignored creeping out of woodwork. Fun fact: Editions is (or used to) render emboldened H2s differently!

**whether it should be unitalicased (or emboldened or underlined or whatevs) should be decided by Design, but the [underlying principle](https://www.quora.com/If-a-book-title-is-italicized-then-what-happens-if-it-is-in-a-sentence-that-is-already-italicized-E-G-I-love-Pride-and-Prejudice-who-doesnt-The-sentence-is-italicized-because-it-is-a-thought) is: no styling choices Editorial chose to employ are ever lost because we decided some elements take on default styling

**Comment by paperboyo** [comment]
Was told [this](https://css-tricks.com/the-double-emphasis-thing/#aa-using-italics-in-emphasized-content-and-vice-versa) might help technically (would we ever wanna look into it). So: [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries#container_style_queries)? But I wouldn’t know…

**Comment by alinaboghiu** [comment]
Done in https://github.com/guardian/dotcom-rendering/pull/11041
