### ISSUE TITLE
Transitioning to Workload Identity Federation for GCP Access

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#11418]
WebEx uses service account keys to access the Google Cloud Platform (e.g. BigQuery)

The following service account keys are active in PROD - most with counterparts in CODE:

- 3 keys used by Grafana (WebEx and DevX)
- 2 keys used by Fastly (WebEx and Commercial Dev)

Data Tech are encouraging teams to move away from service account keys and use [Workload Identity Federation (WIF)](https://cloud.google.com/iam/docs/workload-identity-federation) instead. WIF provides secure access to GCP resources without managing keys, which reduces risks, improves compliance, and simplifies access management. Some teams that have done this transition successfully in the past are Ophan, Personalisation, and Data Science.

For any questions or assistance, please feel free to reach out to Data Tech.

**Comment by arelra** [comment]
@Jakeii is working on this from Commdev side

**Comment by rowannekabalan** [comment]
It's looking like neither Fastly nor Grafana support WIF yet. Checking with Data Tech whether there's any further action to take.

**Comment by rowannekabalan** [comment]
Grafana doesn't support WIF so no further action.
Fastly doesn't support WIF either, but they support [service account impersonation](https://docs.fastly.com/en/guides/configuring-google-iam-service-account-impersonation-for-fastly-logging) which allows us to do keyless auth. We will move our Fastly logging endpoints to use IAM roles instead of keys.
