### ISSUE TITLE
[BUG] Show / Hide container buttons sending wrong events to Ophan

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#11488]
The `toggleContainer` function in the `ShowHideContainers` component seems sets the `data-link-name` attributes correctly but when clicking on the button on a front container, the click event looks like the opposite of what should happen ("Hide" sends event for "Show" and vice versa - see attached video).

https://github.com/guardian/dotcom-rendering/blob/037b0ceb7fbcbefcabc9d8ab53e24e348daa5cde/dotcom-rendering/src/components/ShowHideContainers.importable.tsx#L25-L46

https://github.com/guardian/dotcom-rendering/assets/43961396/68fde9a4-bbee-4f1b-981e-6aaef2886eb3

**Comment by mxdvl** [comment]
I think @guardian/ophan may be able to advise, here. There’s no guarantee that our systems will respond to the click and change the `data-link-name` attribute quicker than `@guardian/ophan-tracker-js` can pick it up.

**Comment by shesah** [comment]
I spoke to Anthony about this and he said he will get back to us on its importance.

**Comment by shesah** [comment]
From Anthony:

_Hey, short answer is that we're making a new tracking source of truth and can document the issue now so that analysts know how to gather the data correctly. It definitely doesn't need to be fixed asap, but it'd be nice to have the right way round down the line.

Also Fairground is talking about removing the feature altogether with Jo now. So it might be a non-issue_
