### ISSUE TITLE
Dropdowns on fronts not working in safari?

### ISSUE THREAD

**Issue by ashishpuliyel** [guardian/dotcom-rendering#11927]
On some versions of safari the dropdowns - "my account" and the edition switcher menu don't seem to be working.

Slightly shortened user-help report below:

> **My Account link not working on Monterey**
> A reader has raised that the 'My Account' link is unresponsive, which I have been able to replicate on browserstack using Safari 15 on Monterey and on my local work Safari.
>
> Browser Information: (browserstack)
>
> Device: Macintosh - Mac OS 10.15.7
> Browser: Safari 15.6.1
> Window Size: 1920 x 1003
> Screen Size: 1920 x 1080
> Adblocker status: Off
>
> recording:
>
> https://drive.google.com/file/d/14-irCGSBxUeVE_Ppjq_qmIVlxmnH0tRt/view?usp=drive_link

**Comment by paperboyo** [comment]
Anecdotal (fully!). For quite a while those dropdowns weren’t working for me on my Firefox for Windows (multiple versions). Nor were Show/Hide container controls or Lightbox. Basically a full-on Javascript meltdown. Clearing caches and site data, disabling all extensions or Incognito didn’t work. Finally, after establishing it works on a fresh browser profile, I nuked my whole profile and all is fine now. I could not establish what was the issue. Console was printing some js error, which I sadly lost, but I remember it was referencing [this](https://github.com/guardian/dotcom-rendering/blob/e447fa7552da81304171d089fa6d2b86e68d8f17/dotcom-rendering/src/components/Metrics.importable.tsx#L216).

I only mention it here, because my completely unlinked main Firefox browser on Mac (multiple versions) occassionally slows theguardian.com to a crawl. 2GB memory used in browser Task Manager. Performance Profile recorded (which I can’t read, really) shows a lot of yellow. But, crucially, javascript works: it’s just eg. Show/Hide takes, like, 4 seconds.

I know this report is of no help. But maybe we have a hole somewhere…

**Comment by ashishpuliyel** [comment]
Apparently this has fixed itself. Unclear if we did anything about it!
