### ISSUE TITLE
Test Liveblog notifications on a physical device

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12287]
Test whether liveblog notifications work on a physical device. Is a test of https://github.com/guardian/dotcom-rendering/pull/12166 and the communication between the DCAR and native layers

**Comment by domlander** [comment]
## iOS

Notifications do not work on an iPad.

- We get the same native alert popup (_You'll recieve alerts for important updates to this liveblog_) when we subscribe and unsubscribe to notifications.
- When subscribing to notifications, then clicking out of a liveblog, then clicking back in again, I see "Notifications off". This indicates that I'm not currently subscribed to the liveblog, which also suggests that clicking the notifications button doesn't actually subscribe the user to notifications.

## Android

Notifications do not work on a Google Pixel 6.

- No native alert when subscribing to notifications (This may be intentional on Android).
- Visual bugs: The notifications component can be slow to render. If the user is subscribed to notifications, it can take a second or two for "Notifications off" to update to "Notifications on". This is probably accentuated for users not on strong wifi connections. It would be good to have some sort of loading state for this component, or to not show it until we know whether the user is subscribed to notifications [needs design input].
