### ISSUE TITLE
Set up cost allocation tagging for S3 so we can breakdown its usage

### ISSUE THREAD

**Issue by SiAdcock** [guardian/dotcom-rendering#12442]

**Comment by marjisound** [comment]
What's done: 

Detected all the buckets that are associated with a cloudformation stack. Then I used a bash script to add `Name` tag to all buckets that are not associated with any cloudformation stack. Then I worked through the stacks that have S3 bucket resource. I will deploy the PRs after the election.

1. Buckets: onionproxy-code-privateconfigbucketonionproxy29334-w2f6clor58go & onionproxy-prod-privateconfigbucketonionproxy29334-xtf2z9vs4qvq
Stacks: OnionProxy-CODE & OnionProxy-PROD
PR: https://github.com/guardian/dotcom-onion-platform/pull/56 

2. Buckets: newsletters-data-prod & newsletters-data-code
Stacks: newsletters-tool-PROD & newsletters-tool-CODE
PR: https://github.com/guardian/newsletters-nx/pull/329 

3. Buckets: wordiply-prod & wordiply-code
Stacks: frontend-PROD-wordiply & frontend-CODE-wordiply
PR: https://github.com/guardian/wordiply/pull/73 
**NOTE & action:** build fails because this app needs to be registered in https://github.com/guardian/riffraff-platform/blob/main/packages/common/src/access.ts 

4. Bucket: gu-money-deals-site
Stack: money-deals-site
PR: https://github.com/guardian/platform/pull/1636 

5. Bucket: cdktoolkit-stagingbucket-1wt8aointypin
Stack: CDKToolkit
No repo - last update 2019 - 
**NOTE & action:**
  No repository 
  Last stack update in 2019
  The bucket has tag aws:cloudformation:stack-id but template doesn’t. So I added the Name tag manually (no drift reported)

6. Bucket: source-design-system
Stack: source-design-system
**NOTE & action:**
  No repository 
  Last update 2019 
  The bucket has tag aws:cloudformation:stack-id but template doesn’t. So I added the Name tag manually


7. Bucket: cloudwatch-logs-management-structuredfieldsbucket-1a3afx9oo71xh
Stack: cloudwatch-logs-management-PROD 
**NOTE & action:** It’s shared https://github.com/guardian/cloudwatch-logs-management  so won’t add the Name tag

8. Buckets: email-artifacts.theguardian.com
Stack: email-campaign-artifacts-PROD 
**NOTE & action:**
  No repository 
  Last update 2018
  The bucket has tag aws:cloudformation:stack-id but template doesn’t. So I added the Name tag manually

9. Buckets: image-url-signer
Stack: image-url-signer-PROD 
**NOTE & action:** repo is archived, we should delete the stack https://github.com/guardian/image-url-signer-lambda
