### ISSUE TITLE
Liveblog meta on mobile has too much left padding

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4153]
Byline, date and share buttons should left align with the bullet points above

![image](https://user-images.githubusercontent.com/1336821/156557449-bdf07882-99bf-4d3d-9e7d-5fcd679f3193.png)

**Comment by iainjchambers-guardian** [comment]
This looks pretty well aligned to me, although there is an inconsistency in that the headline uses px and the metadata uses rems so that might be causing the issue on some devices. @oliverlloyd could you please post a link to an article where you can see this issue?

<img width="372" alt="image" src="https://user-images.githubusercontent.com/99400613/159520872-e7fcec48-ef22-4b95-b647-2382e2a7da99.png">

**Comment by oliverlloyd** [comment]
Is that DCR? Pleasingly, it's very hard to tell but I think that's an AR screenshot?

This [article](https://www.theguardian.com/world/live/2022/mar/22/russia-ukraine-war-zelenskiy-urges-talks-with-putin-biden-flags-clear-sign-russia-considering-chemical-weapons-live) (on DCR) has the additional space to the left at mobile

**Comment by iainjchambers-guardian** [comment]
Right ok, didn't realise this wasn't an AR ticket, I'll leave that to someone on the DCR team so I don't step on anyone's toes 👍

**Comment by oliverlloyd** [comment]
I mean, you're very welcome to run with it if you want to - it's all up for grabs.
