### ISSUE TITLE
Ads On Apps Deadblogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4238]
Ads on the apps are rendered natively. In AR we provide placeholders and then report their locations to the native layers via Bridget.

In normal articles these placeholders typically appear every few paragraphs. In live and dead blogs we'll instead want them to appear as placeholder _blocks_ in the list of content blocks. The ads themselves will then still be inserted via Bridget as normal.

Let's talk to the Commercial team to figure out the best algorithm for deciding how many blocks should be placeholders and where they should appear.

**Comment by SiAdcock** [comment]
Hi @JamieB-gu, thanks for raising this, and I look forward to seeing AR-rendered liveblogs and deadblogs soon!

> Let's talk to the Commercial team to figure out the best algorithm for deciding how many blocks should be placeholders and where they should appear.

Ought the plan be to render ads in LiveBlogs and DeadBlogs in the same positions as they are currently rendered by mobile-apps-article-templates? If I'm not mistaken, MPUs are currently inserted [before the 2nd and 7th block](https://github.com/guardian/mobile-apps-article-templates/blob/70b8eb9456e90ebd94801d1b35e7ac3ee9a51cf6/ArticleTemplates/assets/js/modules/ads.js#L72-L83).

Alternatively, you might be considering the migration as an opportunity to revisit this approach. If so, I'd be interested to hear more about the thinking behind this 😊

Note that I'm going on holiday for 2 weeks after 29/7/22, so it would be helpful to keep @guardian/commercial-dev in the loop.

**Comment by JamieB-gu** [comment]
> Ought the plan be to render ads in DeadBlogs in the same positions as they are currently rendered by mobile-apps-article-templates?

Yup we can do that if you think that's best 👍.

> MPUs are currently inserted after the 2nd and 7th block.

Should we do this on each page of the blog?

**Comment by ashishpuliyel** [comment]
Can we come back to you early next week with more canonical advice, please? I think we've been wanting to revise the 2/7 rule for some time (because it's quite different from the web behaviour). But I'll need to do some digging before I can recommend a new rule.

**Comment by ashishpuliyel** [comment]
@JamieB-gu I know this is a lot later than 'early next week'. Sorry. For now lets go with a modified version of 2nd and 7th:
2nd and every 5 blocks after that. So 2nd & 7th ... & 12th & 17th etc.

It's taken a while for me to come back with this not particularly insightful answer because the truth is this isn't ideal: on some news content the ads will be very far apart (a block that includes a twitter embed is basically a full screen tall, 5 of those is a long way without ads), and on sports blogs, for example, the ads will be comparatively close together. But until we can propose a better rule that counts characters in the blocks (like what we do for articles), and is smarter about embeds and the link this will have to do.

**Comment by JamieB-gu** [comment]
@petternitter to talk to Commercial about this.
