### ISSUE TITLE
Create commercial dashboard for Fronts

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4416]
Ask D&I to create a ad view in tableau for Fronts.

Do Commercial need to input into this or can this follow the existing dashboards?

**Comment by guyparr** [comment]
@oliverlloyd just to confirm, this is to support the DCR migration? So you'd be after the same metrics as for previous migrations (ie articles and liveblogs)?

**Comment by VDuczekW** [comment]
@guyparr hey just going through the board - is there an update

**Comment by guyparr** [comment]
I've just spoken to Yen. The dashboard is ready to go but there currently isn't any data as it relies on there being page views with 'dcrCouldRender' in experiences. This is because it compares page views that are rendered by dcr to those that could have been rendered by it. Can you confirm that this is set up/will be set up?

**Comment by VDuczekW** [comment]
@jamesgorrie @OllysCoding @mxdvl see Guy's comment

**Comment by VDuczekW** [comment]
not serving pages at mo so no data 
- @jamesgorrie to make sure we have all set up and will get back

**Comment by VDuczekW** [comment]
Guy is checking we can filter rendering tier
