### ISSUE TITLE
Fronts release plan

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4451]
Having an initial plan for how we might release fronts. 

- [x] Are any fronts simpler than others? 
- [X] What fronts should we focus on: `/international`
- [x] #4720
- [x] What % of traffic shall we release to?
- [x] Could we serve CAPI fronts first as simpler?
- [x] Could we create a front that only supports a subset of containers and work with editors in using those fronts?

**Comment by paperboyo** [comment]
> a subset of containers

Who knows? Maybe some data or some people (CP? fronts editors?) would be able to instantly say that some of these aren’t ever really used (and could be deprecated):

![image](https://user-images.githubusercontent.com/6032869/160914088-de4cfddd-4f4c-4b1e-927a-3c66fbcb4c0d.png)

Also, I know @akemitakagi had a long, hard look at fronts recently, worth a chat? Some of the stuff here is still very, very cool: http://www.katstubbings.com/theguardian. How much we’ve stuck to it since then… an open question.

**Comment by oliverlloyd** [comment]
Marking this as done as I think we have answers for all the questions and plan to move forward
