### ISSUE TITLE
`Show More`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4604]
This button, shown at the bottom of containers, will make an api call to fetch in more content that can be appended to the bottom of the container.

The layout for the expanded content is currently the same, simple, one.

### Questions
How is the api url created? Is this passed down or constructed client side?
Do we need a `?dcr` version of these endpoints to allow json to be passed back or should we take the same approach that we did for key events and pass back html?

**Comment by bryophyta** [comment]
Questions about desired functionality

## Container layout

As far as I can tell, the current functionality implemented by Frontend is to always return the 'show more' cards as a slice of what I think we call `smallCards` in DCR, i.e. they never have images etc. They are also always laid out in equally-sized columns (3 on desktop, going down to 2 or 1 on tablet/mobile) regardless of the layout of the parent* container. See e.g.:
![Screenshot News sport and opinion from the Guardian's UK edition The Guardian](https://user-images.githubusercontent.com/37048459/170246944-05bed8ae-2f76-41df-8f1c-524775d39d1f.png)

Is this a feature that we want to preserve when this functionality is moved to DCR, or do we need to plan for adding more flexibility to the layout of the 'show more' slice, depending on the parent container or other factors?

## Filling the container

Given that the standard layout described above is always used for 'show more' slices, and given the number of extra articles isn't always a multiple of both 2 and 3, we sometimes end up with blank slots in the 'show more' container (see above for a gap at the end, and also below for a gap at the beginning -- although I'm guessing the latter is due to a separate bug?)

Is this fine, or do we need to think about how to either adjust the layout, or else constrain the number of extra articles, to prevent this kind of gap? 

!['Show more' section with gap at beginning of list](https://user-images.githubusercontent.com/37048459/170248418-fdeaf97d-3b74-4aa4-b487-5eee467c8981.png)

**Comment by oliverlloyd** [comment]
> adjust the layout

DCR actually [already has container layouts](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsLayout.tsx#L14) designed for this exact situation. We could just repurpose that code here?

**Comment by bryophyta** [comment]
@HarryFischer do you have any thoughts on the above from a design perspective? At this stage in the process I'm not sure what our options will be for adding alternative layout style options to 'show more' containers, but if it's desirable to do to, or to use a different fixed layout than we're currently using, then that would be good to know and we can see whether it's possible to add in

**Comment by HarryFischer** [comment]
@bryophyta If it's possible then it would be nice to adjust the layout to fill the space. Feels like it could get messy if there are 4 stories in there - 3 along the top and 1 super wide below? Or would it stack 2 and 2? 
If it's not possible then as long as they flow from the top left I'd just use the 3 column cards as we have in frontend

**Comment by oliverlloyd** [comment]
> If it's possible then it would be nice to adjust the layout to fill the space

It's defo possible. We do it already for related content at the bottom of articles (the non carousel container)

**Comment by oliverlloyd** [comment]
@HarryFischer is there a reason these additional cards don't show images?

**Comment by HarryFischer** [comment]
I think it gets too tall with images @oliverlloyd 
At the moment Opinion on UK front has 12 stories inside 'show more' so I think it's good to just show headlines

**Comment by paperboyo** [comment]
> If the main aim is to draw in visitors who have a particular interest in the container's content, should we be thinking about using the 'show more' section to lead interested users towards the 'homepage' for sections which have them (like Opinion)? (At the moment there is a link to 'All Opinion' from the Opinion container on `/commentisfree`, on desktops, but it's quite small and not integrated with the 'show more' functionality.)

This is a very valid observation (these “treats” are a mess, added manually, serving a variety of unrelated purposes, from commercial to fundamental navigation, like here and are desktop-only like in 1976). Another device is container-names-as-links (also manual, because fronts cannot currently render arbitrary CAPI query). At least the second point I hope could be sorted in DCR fronts – so that all container names can be links automatically, leading to fronts even for curated containers (for those, fronts data may need to be stored differently, though).

OK, this comment isn’t particularly relevant to the issue at hand, so I will stop, but wanted to applaud the thinking!

**Comment by bryophyta** [comment]
Quick additional update about existing functionality.

I'm not sure if this is documented elsewhere already, but given that it relates to some of the layout issues mentioned above it seems worth noting here.

I was investigating what would happen if the 'show more' button was clicked a significant time after the front was initially loaded, i.e. after the front had been changed. My hypothesis was that we might see cards duplicated between the older main container and the newer show more content, if stories had been pushed 'below the fold' since the main content was loaded.

In fact, it looks as though Frontend is able to work out which cards are already rendered in the main container, and so doesn't return duplicates. However, from observing a couple of cases it looks quite likely that it's substituting a blank card in the place of the would-be duplicates, which can then cause the gaps at the _beginning_ of the 'show more' section which we've noted above. (See screenshots below.)

I haven't tracked the process all the way through in light of this yet, but I thought it was worth mentioning here in case it's a recognised problem, or if anyone who's worked on the endpoint before has any insight into this behaviour.

<hr />

*Left: Page loaded at 8, with 'show more' clicked at 8.30. Right: Page loaded fresh at 8.30.*

<br />
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/37048459/170939327-4d4ab798-5065-4d38-b34a-b6605f700aac.png">

<hr />

*Top: Page loaded at 8, with 'show more' clicked at 8.30. Bottom: Page loaded fresh at 8.30.*
<br />
<img width="738" alt="image" src="https://user-images.githubusercontent.com/37048459/170940784-ba50830b-39ed-4f75-b6f2-3273beb38a8c.png">

**Comment by ioannakok** [comment]
Some functionality I've noticed:
1. User clicks `Show More`
2. Call to fetch the extra cards
3. User clicks `Less`
4. User clicks `Show More`
5. No second call 


1. User clicks `Show More`
2. Extra cards are rendered
3. User refreshes
4. The container is rendered with the extra cards

Do we perhaps want to split separate tickets and / or PRs to address those?

**Comment by ioannakok** [comment]
1. User clicks `Show More`
2. Extra cards are rendered
3. User refreshes
4. The container is rendered with the extra cards

Do we perhaps want to split separate tickets and / or PRs to address those?

**Comment by ioannakok** [comment]
Moving to blocked as there are some discussions related to #5427
