### ISSUE TITLE
Drop caps in DCR

### ISSUE THREAD

**Issue by marsavar** [guardian/dotcom-rendering#4725]
I closed https://github.com/guardian/dotcom-rendering/issues/4542 as all drop cap rules have been implemented in AR.

In DCR, the following two rules have not been implemented yet:

- Don't render drop cap if the paragraph starts with the letter "I"
- Don't render drop cap if the first word in the paragraph is shorter than three characters.

For reference, AR's implementation can be found here:
https://github.com/guardian/dotcom-rendering/blob/main/apps-rendering/src/renderer.ts#L225-L246

cc @HarryFischer

**Comment by MarSavar** [comment]
Here is an example of an article where the drop cap shouldn't be rendered because it starts with a word that's only 2 chars long: https://www.theguardian.com/sport/2022/may/03/jacob-blake-interview-injuries-police-shooting-kenosha-nba-players

AR doesn't use a drop cap here (as intended): https://mobile.guardianapis.com/rendered-items/sport/2022/may/03/jacob-blake-interview-injuries-police-shooting-kenosha-nba-players

**Comment by jamesgorrie** [comment]
There has been a change on this. As per [this PR](https://github.com/guardian/dotcom-rendering/pull/7490) we're going to be removing the 3 letter word and starts with "I" rule. 

The reasoning is that we don't have that rule anywhere else, and this would make DCR and apps consistent, but also consistent with print and interactive work.
