### ISSUE TITLE
Change Guardian VR interactive page

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4820]
We need to make some changes to the Guardian VR page. [The code is kept in this repo](https://github.com/guardian/interactive-guardianvr-hub/tree/master/src/assets).

The reason is the app is being removed from app stores as it is no longer supported.

We would like to keep the page as a record of what was done.

Here are the changes:

---

<img width="757" alt="image" src="https://user-images.githubusercontent.com/31692/166648943-dcbd5b37-c9d4-4f3e-87c4-df16194745e6.png">

Remove both CTA's and first sentence of the subheader, thereby leaving only:  "Step inside the story with a new world of digital journalism."

---

<img width="1778" alt="image (1)" src="https://user-images.githubusercontent.com/31692/166649004-c2b9aa38-76e6-4ac4-a95c-ad13ba9b8550.png">

Delete all of this

---

<img width="278" alt="image (2)" src="https://user-images.githubusercontent.com/31692/166649082-116a7eb3-847b-4328-aaeb-dd7beb1b1295.png">

Delete all references to the app in each episode. Each episode is accessed by the +Explore buttons. (There should be 13 'download the app' references in total for all 13 episodes). 

---

**Comment by jamesgorrie** [comment]
Needs write permissions on the repo @jamesgorrie

**Comment by jamesgorrie** [comment]
Could we render this page in DCR rather than having to work out how to do this in the current state.

**Comment by jlieb10** [comment]
We are building an /email-newsletters static page on DCR in the near future so can refer to that work on this.

**Comment by AshCorr** [comment]
I'm wondering if this would be the best choice for a page to migrate to DCR, considering that its a legacy page it feels like it possibly shouldn't be something that we spend effort moving to DCR. An alternative suggestion might be to move this [page](https://www.theguardian.com/technology/ng-interactive/2018/may/15/the-guardian-app) over instead, we pressed it a while back due to some issues but its still referenced in a subnav of the site.

The VR page turns out to be using Node 9 and Bower, with both of those installed it was a bit of a breeze to actually make the required changes.

**Comment by AshCorr** [comment]
Completed in https://github.com/guardian/interactive-guardianvr-hub/pull/3
