### ISSUE TITLE
Create Athena table to query json logs from fastly

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#5215]
While investigating https://github.com/guardian/dotcom-rendering/issues/4910 we figured out that currently: 

1. We don't have a straightforward way to query fastly logs coming from `www.theguardian.com/`. --> 
- Create a table in Athena to read them as JSON. At the moment the data is sent to S3 as invalid JSON

   We need to either find a way to convert this to JSON (check: https://docs.aws.amazon.com/athena/latest/ug/parsing-JSON.html#converting-native-data-types-to-json) or create a new fastly logging configuration that will send the logs to a new bucket in JSON only format.
   This could also be a good time to think about what data would be *useful* to store. The current logs don't store that much data, is there anything else we might need? Anything that's in there currently that we _don't_ need?

- Create a table for the redirects (?) (see below).

2. We have two tables to query fastly data coming from `www.gu.com` (`fastly_logs` and `fastly_logs_redirect`) --> 

  - Find out who's querying those tables
  - Delete them? We won't need them after 3 months as www.gu.com got decommissioned on the 31st of May and the bucket stores the data for 90 days.

This would also save us some money: https://aws.amazon.com/athena/pricing/

**Comment by bryophyta** [comment]
Re: Option 1. Just adding a couple of points for reference here (very provisional):
- It looks like even after removing the prefix (e.g. `<134>2022-06-15T00:01:36Z cache-lcy19282 s3-log-no-keys[87151]:`) some of the remaining json-like strings might not actually be valid json because they contain a value: `""-""`. Possibly some deserialisers can overcome this, but if not then we'll have to do further preprocessing to get around these values.
- You can use some fairly basic [regex functions in Athena SQL](https://docs.aws.amazon.com/redshift/latest/dg/REGEXP_REPLACE.html) which might help implement a preprocessing step within the query itself.
- Alternatively, there is [a regex-aware SerDe library](https://docs.aws.amazon.com/athena/latest/ug/regex-serde.html) available which (if I've understood correctly) looks like it's very well suited to the purpose if we can get the regex right.

**Comment by bryophyta** [comment]
@ioannakok @jamesgorrie I think I missed some recent discussions in the team about data and observability, so not sure whether this is something that fits with our current priorities/plans, but thought it might be worth checking in on this. In theory it feels like this could be a fairly quick piece of work once we decide on an approach -- is it something that would be worth trying soon, or is it not a big value-add for us at the moment?

**Comment by ioannakok** [comment]
An alternative would be to extract the log line as a string and not attempt to parse it as JSON. `fastly_onion_logs` table is able to query the onion logs coming from fastly and has been set up this way.

**Comment by bryophyta** [comment]
We have now created a new fastly logging config which sends valid json to S3, and have created an Athena table to read from it. Closing this issue accordingly, and creating a new issue to provision the table in code: #6986 6986
