### ISSUE TITLE
Newsletter sign up component in article

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5218]
Newsletters would like to render the sign-up component in something that is not a thrasher.

**e.g.**
<img width="647" alt="Screenshot 2022-06-17 at 14 25 44" src="https://user-images.githubusercontent.com/31692/174307656-b256939a-68a1-4e5e-8bd3-bede16740b32.png">

## Summary of the solution
- Tag an article with a newsletter tag
- Render the newsletter signup component directly from DCR
- Investigate if we might need to add something like a placement marker in Composer

**Comment by jfsoul** [comment]
I think a part of the rationale for the current implementation is to sandbox the form from the rest of the page (where 3rd party scripts have DOM access) via an iframe. Maintaining/improving that sandboxing would be ideal (I'm not sure the current implementation achieves it because it is same-domain)

**Comment by oliverlloyd** [comment]
Closing as this work is complete.
