### ISSUE TITLE
The in-memory cache is populated with `curated-content`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5567]
Part of: #5349 

### Background
This ticket and:
* https://github.com/guardian/dotcom-rendering/issues/5842
are to create an agent that fetches the content to populate this carousel (e.g. More from Sport, Headlines, Culture etc.) at the onwards section of articles / liveblogs:

![image](https://user-images.githubusercontent.com/19683595/186444604-c82d194a-8af4-46ca-94de-f7cff1919cb5.png)

![image](https://user-images.githubusercontent.com/19683595/186445412-53958a61-4811-4f72-9583-202a0c7411f4.png)

## Todo
An agent runs that populates the in-memory cache with the data used for onwards.

**Comment by bryophyta** [comment]
Current setup:
-  DCR queries the `container/data` endpoint in the `facia` app.
- Facia controller [gets a pressed page from S3](https://github.com/guardian/frontend/blob/a381962873baa506126f7b2cd3128c57dc0485fa/facia/app/controllers/FaciaController.scala#L400-L413) and gets the container from it (sounds familiar.. 🤔)
- Then it sends back a list of the first 10 trails from the (deduped) collection (again with its own data model, it looks like?

**Comment by bryophyta** [comment]
It looks like currently we are choosing what container to fetch by [looking at the article pillar](https://github.com/guardian/dotcom-rendering/blob/84efc7703849f86a6c3fcb06458564e08a7d4d47/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L115-L158), and getting the main container (for the edition) for that pillar, if there is one. The container ids are [stored in a hard-coded map](https://github.com/guardian/dotcom-rendering/blob/84efc7703849f86a6c3fcb06458564e08a7d4d47/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L78-L109). Do we know whether this is something we want to preserve moving forwards, or do we need to build in the option of fetching container ids dynamically, either to add more containers or because the ids might change over time?

cc. @oliverlloyd I feel like you might have some insight here?

**Comment by oliverlloyd** [comment]
> Do we know whether this is something we want to preserve moving forwards, or do we need to build in the option of fetching container ids dynamically, either to add more containers or because the ids might change over time?

My instinct here would be to not make big changes to how content is fetched as part of moving it but I agree that having these ids hard coded is not great.

I think it is worth a time-boxed investigation to see what level of effort it might be to fetch these dynamically but it's been over a year without changes here and with everything working so arguably this hard coded solution is solid.

**Comment by bryophyta** [comment]
So I think that [Alina's branch](https://github.com/guardian/frontend/compare/main...cache-curated-content) implements this sort of pattern already actually! I didn't know about it before so just looking through it now

**Comment by ioannakok** [comment]
Draft PR: https://github.com/guardian/frontend/pull/25423

Tasks to complete this ticket:
* Move `facia/app/services/CuratedContentAgent.scala` in `common` so that it can be called from `ArticleController`
* Move https://github.com/guardian/frontend/blob/main/facia/app/controllers/front/FrontJsonFapi.scala to `common` because it is called by `CuratedContentAgent.scala`
* Refactor `CONTAINERS_WITH_EDITION` Map in `CuratedContentAgent` so that it is of type `Map[Theme, Map[Edition, String]` (Similar to: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L80). This will allow us to fetch the curated content from the cache with the information we have in `ArticleController` making similar call like here: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L127
* Put curated content in `DotcomRenderingDataModel` and send it to DCR

**Comment by ioannakok** [comment]
Closing. See epic: https://github.com/guardian/dotcom-rendering/issues/5349
