### ISSUE TITLE
Dropcaps And Horizontal Rules

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5967]
Dropcaps can currently appear on the **first paragraph** of a piece and on **any paragraph following a horizontal rule**, typically signified by a dinkus: "* * *".

The rules for when one of these paragraphs is permitted to start with a dropcap are as follows:

1. The piece is a particular format that permits dropcaps (immersive, feature, interview etc.)
2. The paragraph must contain at least 200 characters
3. The first word must be at least 3 characters long, and must not start with an "I" or a punctation mark (excluding quotes)

Should rules 2) and 3) be applied for paragraphs following a horizontal rule? If they are then some articles will have a mix: some paragraphs that are prefixed by horizontal rules will have dropcaps, some others that are also prefixed by horizontal rules will not. This may be correct behaviour, or it may be something we want to change.

| Dropcap | No dropcap (rule 3, first word too short) |
| - | - |
| ![dropcap] | ![no-dropcap] |

[dropcap]: https://user-images.githubusercontent.com/53781962/188928828-de7b60a0-6740-49eb-97f3-4ee64c39bb38.jpg
[no-dropcap]: https://user-images.githubusercontent.com/53781962/188928834-501da420-5638-451d-bace-3b7ecf7d3f4a.jpg

**Comment by JamieB-gu** [comment]
@HarryFischer @ajbreuer @paperboyo what are your thoughts on this?

**Comment by paperboyo** [comment]
My 2gr is the logic for that should be the same between platforms, so that it’s predictable and could be added to eg. [this doc](https://sites.google.com/a/guardian.co.uk/esd/tips/drop-caps-when-and-how-they-appear).

It may indeed suggest a structure where there isn’t one if the drop caps further down the article are not there because of 2 and 3 (although I have no idea how common would 3 be in real content and how bad it may look when that happens).

But the decision, obviously, rests with Design.

**Comment by VDuczekW** [comment]
will discuss this with Alex on Monday - may be part of the design review work

**Comment by jamesgorrie** [comment]
#7490

**Comment by rhiannareechaye** [comment]
Looks like this has been addressed by James' ticket https://github.com/guardian/dotcom-rendering/pull/7490
