### ISSUE TITLE
Update services using Ubuntu 18.04

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#7268]
[From April 2023, standard support for Ubuntu 18.04 (Bionic Beaver) ends](https://ubuntu.com/about/release-cycle). This means it will receive fewer updates.

We have a number of services using Ubuntu 18.04, and we must move to Ubuntu 20.04, or 22.04 before April 2023 to ensure regular receipt of updates.

There are two Amigo recipes we could update that should cover most of what we use:
https://amigo.gutools.co.uk/recipes/frontend-router-ARM
https://amigo.gutools.co.uk/recipes/frontend-base-ARM-java11

**Comment by jamesgorrie** [comment]
@georgeblahblah would be interested in pairing on this when someone picks it up

**Comment by georgeblahblah** [comment]
[`frontend-base-ARM-java11`](https://amigo.gutools.co.uk/recipes/frontend-base-ARM-java11) installed the `python-pip` package from `apt-get`. This package is not found for Ubuntu 20. I can't see anything in `frontend` using `python` or `pip`, so perhaps we can omit it?

Ubuntu 20 and above come with `python3`

**Comment by georgeblahblah** [comment]
For `frontend`, I've created a recipe with Ubuntu 20 (Focal): [`ubuntu-focal-frontend-base-ARM-java11`](https://amigo.gutools.co.uk/recipes/ubuntu-focal-frontend-base-ARM-java11).

I've dropped the [`cloud-watch-logs`](https://amigo.gutools.co.uk/roles#cloud-watch-logs) role because it's deprecated. I've replaced it with [`cloud-watch-agent-logs`](https://amigo.gutools.co.uk/roles#cloud-watch-agent-logs). `cloud-watch-agent-logs` does not yet support Ubuntu 20 using an ARM processor ([https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html)).

I'll raise a PR soon to use the new recipe in `frontend`, so we can test on CODE.

**Comment by georgeblahblah** [comment]
Completed in https://github.com/guardian/frontend/pull/25963 and https://github.com/guardian/platform/pull/1517
