### ISSUE TITLE
`fixed/medium/slow-XIIMPU` second slice rendering incorrectly

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7295]
> [/inpictures](https://www.theguardian.com/inpictures?dcr) Highlights of the day container
Not sure what’s wrong here - the single card should go full width. Maybe linked to boosting behaviour? See frontend

<img width="607" alt="image" src="https://user-images.githubusercontent.com/37048459/221598189-a0e85b70-caf2-4fb5-9db5-7a951c193c14.png">

**Update**

I don't think that this is related to boosting behaviour, because it looks like it's a fixed container (`fixed/medium/slow-XIIMPU`).

From what I can tell, the issue is that Frontend doesn't render the second slice if at all unless there are more than 3 story cards. Given this, it doesn't render the ad slot when there are only 3 stories. DCR is rendering the ad slot on the second slice even if that slice is otherwise empty. So if we're following Frontend we should just exclude the ad from this container because there are only 3 cards in it.

(There's also the difference that when there's only one card on the second row it's not stretching on DCR, but this is a separate issue and should be an easy fix.)

|No. Cards|Frontend|DCR|
|-|-|-|
|3|<img width="1294" alt="image" src="https://user-images.githubusercontent.com/37048459/223714276-45e9f670-78fd-4738-b966-c4deb4ec5583.png">|<img width="1292" alt="image" src="https://user-images.githubusercontent.com/37048459/223714472-464446ed-fadc-4ea3-8ad0-2468fbf02c00.png">|
|4|<img width="1285" alt="image" src="https://user-images.githubusercontent.com/37048459/223714942-53a5826a-6812-4b0d-b989-a83351c9c0da.png">|<img width="1288" alt="image" src="https://user-images.githubusercontent.com/37048459/223714787-dbd1afdd-c644-4c00-be40-04dce9b5e244.png">|

**Comment by AshCorr** [comment]
It seems like the root cause of the issue is that the `fixed/medium/slow-XIIMPU` container is meant to have 12 cards but in this instance its only being used with 2. We've previously discussed not supporting a dynamic number of cards in our fixed containers due to how complicated it would make them so I'm somewhat hesitant on adding support for less cards in `fixed/medium/slow-XIIMPU`

Will reach out to CP and see if theres any chance they could use `dynamic/slow-MPU` for this container instead as it seems to yield similar looking results design wise.

**Comment by bryophyta** [comment]
> Will reach out to CP and see if theres any chance they could use dynamic/slow-MPU for this container instead as it seems to yield similar looking results design wise.

This sounds like a good solution! 🤞🙂
