### ISSUE TITLE
Take into account `isPaidContent` in merchandising high logic

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7619]
Once DCR [supports `isPaidContent`](https://github.com/guardian/dotcom-rendering/issues/5945) we need to make sure we're taking this into account in the logic that decides the position of merchandising high. See [frontend logic](https://github.com/guardian/frontend/blob/main/common/app/views/support/HtmlCleaner.scala#L836-L849).

**Comment by rhiannareechaye** [comment]
There are two merchandising ad slots (merchandising high is the top one). We can't have 'paid content' and then merchandising content together so we need some logic which moves this slot when it goes next to a paid content container. This would be either small or medium - a lot of the logic is already there

**Comment by chrislomaxjones** [comment]
As far as I can tell, the logic laid out in @rhiannareechaye's comment above isn't implemented on Frontend. I captured the image below from https://www.theguardian.com/education?dcr=false, which shows a labs container next to the merchandising high slot.

![Image](https://github.com/guardian/dotcom-rendering/assets/8000415/9a9b683a-f531-41ba-9cdd-34c5617fd308)

I checked with @Amouzle and I think from a Commercial perspective we're happy to keep parity with Frontend on this one, rather than try and build an enhancement.

Assuming no objection from WebEx, we can close this ticket as not planned?
