### ISSUE TITLE
Timebox 2 hours to investigate poor CLS

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7756]
Hi Peter,

I was going through the CWV report on GSC and found a group of pages with poor CLS. These are mostly old articles using some past site format (See [here](https://www.theguardian.com/century/1990-1999/Story/0,,112749,00.html), [here](https://www.theguardian.com/society/salarysurvey/table/0,12406,1042677,00.html), [here](https://www.theguardian.com/century/1990-1999/Story/0,,112749,00.html)) and seemed to have only started appearing as an issue back in April. The main commonality is that all of these links are .html format. 
image.png

I'm not entirely sure if these pages will effect our overall search authority, but figured it was worth flagging in case this wasn't a known issue. 

Let me know what you think and if I should bring this up to anyone else.

**Comment by jamesgorrie** [comment]
These pages are pressed with the pressing tool, and pressed from R2 which has been decommissioned.

Because of this, We have no way of changing the underlaying content that was pressed, and there be dragons on editing this content directly (not very scalable).

We could just stop Google crawling this content, but that almost defeats the point, as we pressed to make it discoverable.

- [] We should reach out to the SEO folk and see if there is a concern that this would break SEO for the site, as opposed to just the specific
