### ISSUE TITLE
Work on other features in DCR: User/…

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7772]
Aside from tests and fixtures:
[HeaderTopBarMyAccount.tsx](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/HeaderTopBarMyAccount.tsx#L77) component to generate identity links 
Also used in getIdapiUserData() 

See [doc](https://docs.google.com/document/d/1tXWq_Cudcs6U7ZvpQhw2VGM1cMFR2DnoWB_kgGq1Pn0/edit#)

**Comment by Georges-GNM** [comment]
Work to do: 
- seeing what data is required, i.e. what dcr needs from user/
-> email address, userId,

- reviewing if that's already present in the data held by the tokens

- if the relevant data is already there then we need to adjust dcr so that it is fetching data from the tokens

- if not, then identity will need to add the data  to the tokens or we'll need to add additional scopes to the dcr identity-auth config and have dcr fetch that data
-> looks like it's only the brazeUuid which needs to be added

**Comment by coldlink** [comment]
PR https://github.com/guardian/dotcom-rendering/pull/7982
