### ISSUE TITLE
Today in focus carousel dots

### ISSUE THREAD

**Issue by arelra** [guardian/dotcom-rendering#8070]
On the front https://www.theguardian.com/international?dcr the carousel dots for the current 'Today in Focus' container are exhibiting buggy behaviour.

At multiple breakpoints the number of dots displayed is incorrect and do nothing when clicked.

![Image](https://github.com/guardian/dotcom-rendering/assets/7014230/a42d8bb7-8eb9-4739-aef8-9e445c3d4e36)
![Image](https://github.com/guardian/dotcom-rendering/assets/7014230/dfee731c-6e4c-4941-a4d3-56707099ec8a)
![Image](https://github.com/guardian/dotcom-rendering/assets/7014230/225d0475-16dc-4552-b5b3-9befe13ebd65)

**Comment by alinaboghiu** [comment]
This is probably because the carousel is not designed for such few cards. We will get more cards in this container once we support DCR 100% and we can change this container to fixed/video

And the carousel dots have always been buggy. I think they are intended more as a guide than accurate representation.

But if there are any improvements we can make that is great!
