### ISSUE TITLE
DCR the heatmap breaks the layout on certain containers

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#8135]
<img width="906" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/91130034/c7d7b065-7ab4-4019-a72f-226fee1862b9">

**Comment by VDuczekW** [comment]
Looks like the issue happens with dynamic/fast with 10 cards

**Comment by ioannakok** [comment]
The issue happens when the 2nd slice of `DynamicFast` is `twoBigs` using [`Card25_Card25_ColumnOfThreeCards25_ColumnOfThreeCards25` ](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/DynamicFast.tsx#L290). We could try and fix it from DCR or as @jamesgorrie noticed we could ask the Ophan team to remove 

```
*,*::before,*::after {
    box-sizing: initial
}
```

from https://dashboard.ophan.co.uk/assets/stylesheets/heatmap-bookmarklet.min.css. This also fixes the issue and I think is quicker.

**Comment by ioannakok** [comment]
Fixed by: https://github.com/guardian/ophan/pull/5456
