### ISSUE TITLE
Support contributor pages

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#8325]

**Comment by OllysCoding** [comment]
contributors index page:
https://www.theguardian.com/index/contributors

**Comment by ioannakok** [comment]
> contributors index page: https://www.theguardian.com/index/contributors

@OllysCoding 👋 👋 👋 Hello! We already render this via DCR. Did you by any chance also mean these pages? https://www.theguardian.com/profile/georgemonbiot. They have a bug with the avatar, I'm going to create a ticket or repurpose this one.

**Comment by OllysCoding** [comment]
Oh wow that's great, I had not realised that work had been done (did it happen after I left & was just not tracked on this issue?!). I considered profile tag pages as part of the original tag fronts work, but you're right there is a bug there that probably needs fixed, but if `/index/contributors` is working, that's what I'd created this ticket for!

**Comment by ioannakok** [comment]
> Oh wow that's great, I had not realised that work had been done (did it happen after I left & was just not tracked on this issue?!). I considered profile tag pages as part of the original tag fronts work, but you're right there is a bug there that probably needs fixed, but if `/index/contributors` is working, that's what I'd created this ticket for!

I _think_ it happened as part of the fronts migration although it is a mystery how since this gets rendered via [applications](https://github.com/guardian/frontend/blob/3ef13d06acc561ad062c7f9c2b605907c54c5358/applications/conf/routes#L50). Maybe there's a redirect to facia at some point. Anyways, thanks for your help! I'm going to close this ticket and create another one for the bug.
