### ISSUE TITLE
Handle "Sub-Palettes" For Dark Mode

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9112]
We still need to figure out how to handle "sub-palettes" on articles. While the main content of an article has a single `ArticleFormat` from which a palette can be derived, the cards in onward content do not and can have a range of different palettes. More information in:

- https://github.com/guardian/dotcom-rendering/pull/7766#issuecomment-1568045424
- https://github.com/guardian/dotcom-rendering/issues/4241#issuecomment-1191322845

**Comment by mxdvl** [comment]
One approach I’ve opted for in `RichLink`s is to create custom properties overrides at the format “boundary”: https://github.com/guardian/dotcom-rendering/pull/9257/commits/3eb2c3ffc957ca2c3e80447074d57cf1a94a7098

Some quick calculations suggest that this approach has some limitations because it requires every single property to be overriden, even if only a subset of them are used. Once we have 150 colours, this would adds [about 4.5kB of CSS per article variation](https://docs.google.com/spreadsheets/d/1FWKCKFidfLIpgrX7mGIoUiHEh3brOkcQLjAuU7qRW0Y/edit).
