### ISSUE TITLE
[Bug]: ~500k failed attempts a day to render the weather widget (onward service)

### ISSUE THREAD

**Issue by jorgeazevedo** [guardian/dotcom-rendering#9385]
### What happened?

This is a follow up to https://github.com/guardian/dotcom-rendering/issues/8233, when we initially detected that onward was serving a lot of errors following the release of the weather feature. Though there was a PR to address it at the time and it did reduce the number of failures considerably, a high number of similar errors continue to occur.

We can see in [onward's availability graph for this year](https://metrics.gutools.co.uk/d/zM0ouzs4z/sli-dashboard-debug-view?orgId=1&var-AWSAccount=frontend&var-Service=frontend-PROD-onward-ELB&from=now%2Fy&to=now&var-Period=1d&var-StageFilter=PROD&var-ElkIndexFilter=logstash-frontend-%2A&var-ElasticSearchIndex=logstash-frontend-%2A&var-App=onward&var-Stack=frontend&var-Stage=PROD&var-ASGName=frontend-PROD-OnwardStack-1WBRIBDSACKQL-AutoscalingGroup-1PZU7S81QUBTQ&var-SLO=none) that the issue first shows up at around July 5th, where the Availability SLI drops to 85%, and [following the fix on July 18th](https://github.com/guardian/frontend/pull/26318) it recovers to about 90% and it's been at around that value ever since.

![Screenshot 2023-11-02 at 10 11 10](https://github.com/guardian/dotcom-rendering/assets/1672034/0bc56816-07d3-48b7-98b3-6d64fd31a19e)

If we look at the [correlation between logs and 5XX errors](https://metrics.gutools.co.uk/goto/4I1KAd4Ik?orgId=1), we can see a very close correlation between instance 5XX and logs with level warn

![Screenshot 2023-11-02 at 10 07 09](https://github.com/guardian/dotcom-rendering/assets/1672034/0ada3831-b935-4ceb-9519-931d3540de9f)

And indeed, if [we look up these logs in kibana](https://logs.gutools.co.uk/s/dotcom/goto/a8077f00-7967-11ee-9fde-f76cdda00c15), we can see that they are almost all messages related to weather.json

```
GET /weather.json failed
Could not match country [Some(XX)], city [Some(XXXXXX)] and region [Some(XX)]to a valid location.
```

### Where is this happening?

I believe this relates to the weather widget on the network front

### What is the impact?

I believe a subset of users in particular locations are not seeing the weather widget, though I'm not sure what the client-side behaviour is when the request for weather.json returns a 5XX

From an alerting perspective, having onward serving 10% of errors as a baseline makes it hard to set an effective SLO alert and detect future outages. It also makes it hard to debug any future outages as the logs have a high number of weather-related error messages.

**Comment by abeddow91** [comment]
We use accuweather to provide data for the weather widget.

When a user country and city can't be found in the accuweather dataset eg (), we fallback to a default city that is mapped to their editions (UK => London, US => New York, AU => Sydney) However, we don't have fallback for the international or europe edition and so any user whose city / country is not avaialble in accuweather who is in the international or europe edition will result in a 5XX error.

Options:

1. **add a default city for these editions**: We use Paris => Europe and London => Interanational for their timezones so we could continue this pattern for the defualt city. CP and Jonathan Haynes have been asked for approval.
2. **Use the capital city for the users country if city is not available**:  Accuweather doesn't have an api to retrieve the capital city from a country code. In order to support this, we would need to build our own dataset that mapped country codes -> capital city -> accuweather ids. This is quite brittle - if anything changed in the chain, these changes wouldn't be reflected in out dataset.
3. **use a less precise city**: we get the users country / city from their fastly headers. Is it possible to get a less specific city from fastly making it more likely it will be found in accuweather?
